name = "Pastoria"
author = "Pastel"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4f9e975132f2cf10d37548c347e3f0bc7eca93032a0c6b0f73a161aac24f4c7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
