name = "Pastoria"
author = "Pastel"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ebbe75fcd836a43140030f28316a9f001b8c0deb65bcffdb8feca9b4b54aeb8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
